#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_dictionaries.py — 由上游 frequency_lists.coffee 生成 MoonBit 词典数据模块

数据源（三选一，按可信度）：
  1. data/upstream/dropbox-zxcvbn/src/frequency_lists.coffee   ← 本脚本解析这个
     （上游 JS 运行时真正加载的文件；Dropbox 官方 zxcvbn 用的就是它）
  2. data/upstream/zxcvbn-rs/src/frequency_lists.rs            ← 双源互证（本脚本断言一致）
  3. data/upstream/dropbox-zxcvbn/data/*.txt                   ← 原始频次文件，**不能直接嵌入**

为什么不能直接用 data/*.txt（历史教训，2026-09-23  reviewer 指出）：
  上游 data-scripts/build_frequency_lists.py 在生成 coffee 之前对 txt 做了四道处理：
    a. 跨词典去重：同一 token 只保留在「rank 最小」的那个词典里；
    b. 短稀词剔除：rank >= 10**len(token) 的词删掉（暴力猜比查词典更快）；
    c. 逗号/双引号词剔除（comma-join 格式的限制，如 'ps8,000'）；
    d. 按上限截断：us_tv_and_film/english_wikipedia/passwords=30000、
       surnames=10000，male_names/female_names 不截断。
  最终 6 表规模：30000/30000/3712/983/10000/19160（共 93,855 词）。
  而原始 txt 是 47023/100000/4275/1219/88799/39070（共 280,386 词）——
  rank 排序完全不同，直接嵌入 txt 会导致 guesses 与上游/Zxcvbn-rs 系统性不一致，
  官方向量与差分对拍在数学上无法通过。

本脚本产出：/frequency_data.mbt
  - 每个词典 N 个 const 多行字符串（MoonBit `#|` 行前缀语法，原始内容零转义）
  - 每个词典一个 list 解析函数（按行 split，rank = 下标 + 1）
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
COFFEE = os.path.join(ROOT, "data", "upstream", "dropbox-zxcvbn", "src",
                      "frequency_lists.coffee")
RUST = os.path.join(ROOT, "data", "upstream", "zxcvbn-rs", "src",
                    "frequency_lists.rs")
OUT = os.path.join(ROOT, "frequency_data.mbt")

CHUNK_LINES = 4000

# (coffee 键名, MoonBit 前缀, 说明, 上游 DICTIONARIES 截断上限, 期望最终词数)
DICTS = [
    ("passwords", "PASSWORDS", "常见密码", 30000, 30000),
    ("english_wikipedia", "ENGLISH_WIKIPEDIA", "英文维基常用词", 30000, 30000),
    ("female_names", "FEMALE_NAMES", "常见女性名", None, 3712),
    ("male_names", "MALE_NAMES", "常见男性名", None, 983),
    ("surnames", "SURNAMES", "常见姓氏", 10000, 10000),
    ("us_tv_and_film", "US_TV_AND_FILM", "美剧/电影词", 30000, 19160),
]

RUST_NAMES = {
    "passwords": "PASSWORDS",
    "english_wikipedia": "ENGLISH_WIKI",
    "female_names": "FEMALE_NAMES",
    "male_names": "MALE_NAMES",
    "surnames": "SURNAMES",
    "us_tv_and_film": "US_TV_AND_FILM",
}


def parse_coffee(path):
    """解析 frequency_lists.coffee：`key: "w1,w2,..."` → {key: [w,...]}（保序）。"""
    src = open(path, encoding="utf-8").read()
    out = {}
    for m in re.finditer(r"(\w+)\s*:\s*\"([^\"]*)\"", src):
        out[m.group(1)] = [w for w in m.group(2).split(",") if w]
    return out


def parse_rust(path):
    """解析 frequency_lists.rs：`const NAME : &str = "w1,w2,...";` → {NAME: [w,...]}。"""
    src = open(path, encoding="utf-8").read()
    out = {}
    for m in re.finditer(r"const\s+(\w+)\s*:\s*&str\s*=\s*\"([^\"]*)\"", src):
        out[m.group(1)] = [w for w in m.group(2).split(",") if w]
    return out


def esc(s):
    """#| 原始多行字符串：内容零转义。仅断言词条内无换行。"""
    assert "\n" not in s and "\r" not in s, "word contains newline"
    return s


def main():
    coffee = parse_coffee(COFFEE)
    rust = parse_rust(RUST)

    # ---- 双源互证：coffee（JS 运行时）与 zxcvbn-rs 常量必须逐词一致 ----
    for key, prefix, _desc, cap, expected in DICTS:
        c = coffee[key]
        r = rust[RUST_NAMES[key]]
        if c != r:
            print("FATAL: %s 与 zxcvbn-rs 的 %s 不一致（长度 %d vs %d）"
                  % (key, RUST_NAMES[key], len(c), len(r)))
            sys.exit(1)
        if len(c) != expected:
            print("FATAL: %s 期望 %d 词，实得 %d"
                  % (key, expected, len(c)))
            sys.exit(1)
    print("双源互证通过：frequency_lists.coffee == zxcvbn-rs 常量（逐词一致）")

    parts = [
        "// Code generated by tools/gen_dictionaries.py — DO NOT EDIT.",
        "// Source: data/upstream/dropbox-zxcvbn/src/frequency_lists.coffee",
        "// (c) Dropbox, Inc. — MIT License — https://github.com/dropbox/zxcvbn",
        "//",
        "// 这是上游 JS 运行时真正加载的词典（经 build_frequency_lists.py 四道处理：",
        "// 跨词典去重 / 短稀词剔除 rank>=10**len / 逗号引号词剔除 / 30000 等上限截断）。",
        "// 与 zxcvbn-rs 的 Rust 常量逐词一致（生成时断言）。data/*.txt 是未过滤原",
        "// 始频次文件，不要直接嵌入。",
        "//",
        "// 生成参数：CHUNK_LINES = %d。" % CHUNK_LINES,
        "",
    ]

    total = 0
    for key, prefix, desc, _cap, _expected in DICTS:
        words = coffee[key]
        total += len(words)
        nchunks = (len(words) + CHUNK_LINES - 1) // CHUNK_LINES
        parts.append("// ---- %s : %s ----" % (prefix, desc))
        for c in range(nchunks):
            chunk = words[c * CHUNK_LINES:(c + 1) * CHUNK_LINES]
            parts.append("///|")
            parts.append("const %s_%02d : String = #|" % (prefix, c))
            parts.extend("#|" + esc(w) for w in chunk)
        fn = prefix.lower()
        parts.append("")
        parts.append("///|")
        parts.append("/// %s 的有序词表（rank = 下标 + 1）。" % desc)
        parts.append("pub fn %s_list() -> Array[String] {" % fn)
        parts.append("  let out : Array[String] = []")
        for c in range(nchunks):
            parts.append("  extend_with_split(out, %s_%02d)" % (prefix, c))
        parts.append("  out")
        parts.append("}")
        parts.append("")
        parts.append("// %s: %d words, %d chunks" % (key, len(words), nchunks))
        parts.append("")
        print("%-18s %6d words -> %2d chunks" % (key, len(words), nchunks))

    parts.append("")
    parts.append("///|")
    parts.append("/// 把一个 const 块按行切成 String 追加到 out。")
    parts.append("fn extend_with_split(out : Array[String], chunk : String) -> Unit {")
    parts.append('  for line in chunk.split("\\n") {')
    parts.append("    let s = line.to_owned()")
    parts.append("    if s.length() > 0 {")
    parts.append("      out.push(s)")
    parts.append("    }")
    parts.append("  }")
    parts.append("}")
    parts.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    print("\n[wrote] %s (%.1f KB, %d words total)"
          % (OUT, os.path.getsize(OUT) / 1024.0, total))


if __name__ == "__main__":
    main()
