#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_dictionaries.py — 把 dropbox/zxcvbn 的原始词典 txt 转成 MoonBit 数据模块

输入：data/upstream/dropbox-zxcvbn/data/*.txt（MIT License, (c) Dropbox, Inc.）
输出：frequency_data.mbt —— 每个词典切成 N 个 const 多行字符串 + 解析/建表函数

设计决策（与上游语义对齐）：
  1. rank = 1-based 行号（build_ranked_dict 的语义；上游 frequency_lists.coffee
     是按行序 comma-join 的，female/male_names/surnames 无频次列，也用行序）。
  2. 重复词"后者覆盖前者"——与 JS 对象赋值、Rust HashMap collect 的语义一致，
     由 build_ranked_dict 的实现自然得到（不预去重）。
  3. 每 CHUNK_LINES 行一个 const，避免单个语法节点过大。
  4. MoonBit 多行字符串语法为"每行 #| 前缀"的原始字符串（官方文档
     language/fundamentals：'use #| to write a multi-line string'，#| 保留
     原始内容、不做转义与插值）。因此词条零转义，反斜杠/引号/保留字安全，
     生成前仍以断言守住"词条内无换行"。
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "data", "upstream", "dropbox-zxcvbn", "data")
OUT = os.path.join(ROOT, "frequency_data.mbt")

# (txt 文件名, MoonBit 标识符前缀, 说明)
DICTS = [
    ("passwords.txt", "PASSWORDS", "常见密码（47k，rank=行序）"),
    ("english_wikipedia.txt", "ENGLISH_WIKIPEDIA", "英文维基常用词（100k）"),
    ("female_names.txt", "FEMALE_NAMES", "常见女性名（4.2k）"),
    ("male_names.txt", "MALE_NAMES", "常见男性名（1.2k）"),
    ("surnames.txt", "SURNAMES", "常见姓氏（88k）"),
    ("us_tv_and_film.txt", "US_TV_AND_FILM", "美剧/电影词（39k）"),
]

CHUNK_LINES = 4000


def load_words(path):
    """读原始 txt：'word<空白>count' 或纯 'word'，统一取第一列（与上游
    build_frequency_lists.py 产出的 comma-join 词表一致）。"""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    words = []
    for line in text.split("\n"):
        line = line.rstrip("\r").strip()
        if not line:
            continue
        # english_wikipedia/passwords/us_tv_and_film 是 "word  count" 两列；
        # female_names/male_names/surnames 只有词列。split()+first 两种情况都对。
        words.append(line.split()[0])
    return words


def esc(s):
    """#| 原始多行字符串：内容零转义。仅断言词条内无换行。"""
    assert "\n" not in s, "word contains newline (generator assumption broken)"
    assert "\r" not in s, "word contains CR"
    return s


def main():
    parts = []
    parts.append("// Code generated by tools/gen_dictionaries.py — DO NOT EDIT.")
    parts.append("// Source: data/upstream/dropbox-zxcvbn/data/*.txt")
    parts.append("// (c) Dropbox, Inc. — MIT License — https://github.com/dropbox/zxcvbn")
    parts.append("//")
    parts.append("// 词典数据：6 个频率表，rank = 1-based 行序。")
    parts.append("// 生成参数：CHUNK_LINES = %d。" % CHUNK_LINES)
    parts.append("")

    for fname, prefix, desc in DICTS:
        words = load_words(os.path.join(SRC, fname))
        nchunks = (len(words) + CHUNK_LINES - 1) // CHUNK_LINES
        parts.append("// ---- %s : %s ----" % (prefix, desc))
        for c in range(nchunks):
            chunk = words[c * CHUNK_LINES:(c + 1) * CHUNK_LINES]
            parts.append("///|")
            parts.append("const %s_%02d : String = #|" % (prefix, c))
            parts.extend("#|" + esc(w) for w in chunk)
        names = ", ".join("%s_%02d" % (prefix, c) for c in range(nchunks))
        fn = prefix.lower()
        parts.append("")
        parts.append("///|")
        parts.append("/// %s 的有序词表（rank = 下标 + 1）。" % desc)
        parts.append("pub fn %s_list() -> Array[String] {" % fn)
        parts.append("  let out : Array[String] = []")
        for c in range(nchunks):
            parts.append("  extend_with_split(out, %s_%02d)" % (prefix, c))
        parts.append("  out")
        parts.append("}")
        parts.append("")
        parts.append("// %s: %d words, %d chunks" % (fname, len(words), nchunks))
        print("%-24s %7d words -> %2d chunks" % (fname, len(words), nchunks))

    parts.append("")
    parts.append("///|")
    parts.append("/// 把一个 const 块按行切成 String 追加到 out。")
    parts.append("fn extend_with_split(out : Array[String], chunk : String) -> Unit {")
    parts.append('  for line in chunk.split("\\n") {')
    parts.append("    let s = line.to_string()")
    parts.append("    if s.length() > 0 {")
    parts.append("      out.push(s)")
    parts.append("    }")
    parts.append("  }")
    parts.append("}")
    parts.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts) + "\n")
    total = os.path.getsize(OUT)
    print("\n[wrote] %s  (%.1f KB)" % (OUT, total / 1024.0))


if __name__ == "__main__":
    main()
